"""добавили признак публикации

Revision ID: 76dec5d2c302
Revises: fd3c53d97ebd
Create Date: 2021-03-20 16:18:15.842566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76dec5d2c302'
down_revision = 'fd3c53d97ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
